source 'https://rubygems.org'

gem 'haml'
gem 'oauth2', '0.9.2'
gem 'sinatra', '1.4.2', :require => 'sinatra/base'
gem 'sinatra-contrib', '1.4.0', :require => 'sinatra/json'
gem 'unicorn', '4.6.2'
gem 'rest-client'
gem 'nokogiri'
gem 'dm-types'
gem 'dm-migrations'
gem 'dm-mysql-adapter', '1.2.0'
gem 'datamapper', '1.2.0'
gem 'rake'